import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the folder structure under `docs/`.
 * Ordering comes from `sidebar_position` in each page's front matter and
 * from the `position` field of each folder's `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
